### ISSUE TITLE
Results with 3D CNN & LSTM with 2D CNN

### ISSUE THREAD

**Issue by JohannesTK** [Megatvini/DeepFaceForgeryDetection#2]
Hey,

Thank you for sharing your results & congratulations on benchmark!

Do you also plan to share the results for 3D CNN & LSTM with 2D CNN?

Thanks & stay healthy,
Johannes

**Comment by Megatvini** [comment]
Hey Johannes, thanks for expressing the interest. Yes, we are working on arXiv preprint that will include results in more detail. Should be out soon.

**Comment by Megatvini** [comment]
Publication link is now available on Arxiv 
51f8a7e
