### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by crankyz** [Megatvini/DeepFaceForgeryDetection#6]
Hi sir,When try to launch evaluation, got this error:
TypeError                                 Traceback (most recent call last)
<ipython-input-7-8d893b46ea72> in <module>
      1 _, val_dataset = read_dataset(
      2     '/home/nika/Desktop/FaceForensics/original', '/home/nika/Desktop/FaceForensics/neural_textures/',
----> 3     transform=transform, max_images_per_video=1, splits_path='dataset/splits', window_size=1
      4 )
      5 

TypeError: read_dataset() got multiple values for argument 'transform'
How to solve it, please help.

**Comment by Megatvini** [comment]
Please have a look at `read_dataset` function definition
