### ISSUE TITLE
How to reproduce results of Benchmark

### ISSUE THREAD

**Issue by ah651** [Megatvini/DeepFaceForgeryDetection#7]
Thanks for your work. 
I see your work from the benchmark(http://kaldir.vc.in.tum.de/faceforensics_benchmark/). However, I don't know how to reproduce results of the Benchmark. I want to know how you deal with the imbalance of real and fake image num in FaceForensics++ (The number of fakes is 4 times that of real). In addition, have you used additional data augmentation? 
I test many models, they behave well on test set, however behave really pool on the Benchmark.This is very weird...

**Comment by Megatvini** [comment]
Hey, thanks for your interest. 

To deal with the class imbalance we just repeated original images 4 times during training and haven't tried any additional data augmentations.

Unfortunately, I have no idea what the problem could be in your case
